"""Public package exports for design-research-analysis."""

from . import dimred, language, sequence, stats
from .dimred import (
    EmbeddingResult,
    ProjectionResult,
    cluster_projection,
    embed_records,
    reduce_dimensions,
)
from .language import (
    LanguageConvergenceResult,
    compute_language_convergence,
    compute_semantic_distance_trajectory,
    fit_topic_model,
    score_sentiment,
)
from .core import (
    ProjectBlueprint,
    build_default_blueprint,
    describe_project,
    normalize_package_name,
)
from .sequence import (
    DecodeResult,
    DiscreteHMMResult,
    GaussianHMMResult,
    MarkovChainResult,
    decode_hmm,
    embed_text,
    fit_discrete_hmm,
    fit_discrete_hmm_from_table,
    fit_gaussian_hmm,
    fit_markov_chain,
    fit_markov_chain_from_table,
    fit_text_gaussian_hmm,
    fit_text_gaussian_hmm_from_table,
    plot_state_graph,
    plot_transition_matrix,
)
from .stats import (
    GroupComparisonResult,
    MixedEffectsResult,
    RegressionResult,
    compare_groups,
    fit_mixed_effects,
    fit_regression,
)
from .table import (
    MapperFn,
    UnifiedTableConfig,
    UnifiedTableValidationReport,
    coerce_unified_table,
    derive_columns,
    group_rows,
    select_column,
    validate_unified_table,
)

__all__ = [
    "DecodeResult",
    "DiscreteHMMResult",
    "EmbeddingResult",
    "GaussianHMMResult",
    "GroupComparisonResult",
    "LanguageConvergenceResult",
    "MarkovChainResult",
    "MapperFn",
    "MixedEffectsResult",
    "ProjectBlueprint",
    "ProjectionResult",
    "RegressionResult",
    "UnifiedTableConfig",
    "UnifiedTableValidationReport",
    "build_default_blueprint",
    "cluster_projection",
    "coerce_unified_table",
    "compare_groups",
    "compute_language_convergence",
    "compute_semantic_distance_trajectory",
    "decode_hmm",
    "derive_columns",
    "dimred",
    "embed_records",
    "describe_project",
    "embed_text",
    "fit_discrete_hmm",
    "fit_discrete_hmm_from_table",
    "fit_gaussian_hmm",
    "fit_mixed_effects",
    "fit_markov_chain",
    "fit_markov_chain_from_table",
    "fit_regression",
    "fit_topic_model",
    "fit_text_gaussian_hmm",
    "fit_text_gaussian_hmm_from_table",
    "group_rows",
    "language",
    "normalize_package_name",
    "plot_state_graph",
    "plot_transition_matrix",
    "reduce_dimensions",
    "score_sentiment",
    "select_column",
    "sequence",
    "stats",
    "validate_unified_table",
]
